### ISSUE TITLE
Windows issue

### ISSUE THREAD

**Issue by MostHated** [Jax0rz/Unity-Hub-Dark-Mode#1]
Hey there,
    I see that the examples are for Mac but no mention of this is only working on MacOS so I assume it should work for Windows as well? I tried to fire it up, the application starts but never actually opens any GUI elements or taskbar service. You only see the app running in the background and then have to force it closed. Is there some adjustments that need to be made to work on Windows?

Thanks,

**Comment by RaffeYang** [comment]
I build this on macOS , I think it should work with windows.If it doesn't work, you can built your dark theme with my guid.

**Comment by RaffeYang** [comment]
[Fixed it](https://github.com/Jax0rz/Unity-Hub-Dark-Mode/releases)

**Comment by MostHated** [comment]
Was this for Hub 2.3.1? I pulled the new changes and tried with the included app.asar but it did the same thing. I then went to releases and got the asar from there and tried it again, but it still did the same thing as before. I closed the hub, replaced the asar file, then tried to open the Hub. It opens the exe and you can see it running in the task manager but no GUI ever comes up, and I don't see the taskbar icon show up. I closed the running processes and put the old asar back and opened it and it opened up as it would normally. 

I can definitely understand if you don't have a Windows install of your own to try it on, so I have no issue trying it out, I just wanted to make sure you knew what was happening.

**Comment by RaffeYang** [comment]
> Was this for Hub 2.3.1? I pulled the new changes and tried with the included app.asar but it did the same thing. I then went to releases and got the asar from there and tried it again, but it still did the same thing as before. I closed the hub, replaced the asar file, then tried to open the Hub. It opens the exe and you can see it running in the task manager but no GUI ever comes up, and I don't see the taskbar icon show up. I closed the running processes and put the old asar back and opened it and it opened up as it would normally.
> 
> I can definitely understand if you don't have a Windows install of your own to try it on, so I have no issue trying it out, I just wanted to make sure you knew what was happening.

I build it on Unity Hub 2.3.1,this is the screen shot:
<img width="1092" alt="Xnip2020-05-18_12-31-58" src="https://user-images.githubusercontent.com/7557357/82174680-015ccf80-9904-11ea-8fab-832d96b8146e.png">
<img width="1092" alt="Xnip2020-05-18_12-33-04" src="https://user-images.githubusercontent.com/7557357/82174682-03bf2980-9904-11ea-8090-b9944536c163.png">
<img width="972" alt="Xnip2020-05-18_12-34-12" src="https://user-images.githubusercontent.com/7557357/82174683-04f05680-9904-11ea-811f-a700690027c4.png">
<img width="1092" alt="Xnip2020-05-18_12-34-29" src="https://user-images.githubusercontent.com/7557357/82174684-04f05680-9904-11ea-8ec2-0146ea3b388a.png">
<img width="1092" alt="Xnip2020-05-18_12-35-22" src="https://user-images.githubusercontent.com/7557357/82174695-0e79be80-9904-11ea-810f-fb9c34a62848.png">

If you can't use it ,you can follow this guid to build it on Widnows
## How to build your owe dark theme

1.  install asar

> Note:Please install [node](https://nodejs.org/en/),then open `powershell`or`cmd` to input the command

```bash
npm i -g asar
```

2. unpack app.asar file

> Note: I don't have a windows ,I think the path is `C:\Program Files\Unity Hub\resources\`

```bash
asar extract app.asar app
```

3. Change the style

Add `DarkUnityHub.css` to `client/dist/index.html` &`client/dist/index-new-project.html`

```html
<head>
    <!-- After <head> -->
    <link rel="stylesheet" href="./DarkUnityHub.css" />
    <!-- Before </head> -->
</head>
``` 
4. Pack file

```bash
asar pack app app.asar
```

5. Replace the app.asar file

> Warning :backup app.asar file
