### ISSUE TITLE
Windows 10 formatting issues

### ISSUE THREAD

**Issue by TCROC** [Jax0rz/Unity-Hub-Dark-Mode#2]
![image](https://user-images.githubusercontent.com/24307049/81226539-02fbce80-8fb9-11ea-975f-760bd187a7d8.png)

These are just a few problems with the dark theme on Windows 10 that I noticed when starting up.

1. The toolbar is still white.
2. Unity logo is black.
3. Strange Transparency over certain buttons and messages.
4. Text appears to overlap in certain areas.

All in all, this is much nicer than the light theme.  Because Unity does not have any updates as to when we will see an official dark theme, we might as well improve on this one.

**Comment by RaffeYang** [comment]
I don't know how to make the title bar to be dark on Windows,but if you're using a Mac ,you can use this step:

- Open Terminal.app, then input

`defaults write com.unity3d.unityhub NSRequiresAquaSystemAppearance 0`

- Before
<img width="1092" alt="Xnip2020-05-15_08-03-56" src="https://user-images.githubusercontent.com/7557357/81997588-c0a25380-9682-11ea-9fc8-a48eb1d39aec.png">

- After
<img width="1092" alt="Xnip2020-05-15_08-04-38" src="https://user-images.githubusercontent.com/7557357/81997597-ca2bbb80-9682-11ea-81ef-1149c606622e.png">

**Comment by RaffeYang** [comment]
[Fixed it](https://github.com/Jax0rz/Unity-Hub-Dark-Mode/releases)

**Comment by RaffeYang** [comment]
> ![image](https://user-images.githubusercontent.com/24307049/81226539-02fbce80-8fb9-11ea-975f-760bd187a7d8.png)
> 
> These are just a few problems with the dark theme on Windows 10 that I noticed when starting up.
> 
> 1. The toolbar is still white.
> 2. Unity logo is black.
> 3. Strange Transparency over certain buttons and messages.
> 4. Text appears to overlap in certain areas.
> 
> All in all, this is much nicer than the light theme. Because Unity does not have any updates as to when we will see an official dark theme, we might as well improve on this one.

If you any Windows related question, please follow this #1
